# NB: this file was automatically generated by Dynare
#     from CK08_simRTM.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(26, 32);
gp = zeros(26, 47, 32);
end
return (rp, gp)
end
