# NB: this file was automatically generated by Dynare
#     from CK08_simRTM.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(26, 32);
gp = zeros(26, 26, 32);
end
return (rp, gp)
end
